### ISSUE TITLE
what's the meaning of this line?

### ISSUE THREAD

**Issue by Azson** [elastest/elastest-webrtc-qoe-meter#1]
https://github.com/elastest/elastest-webrtc-qoe-meter/blob/0b7e5379b4181d84c5ac41547443ff9f498fa2db/scripts/calculate_qoe_metrics.sh#L361
I find that I can not handle the video with size 1920x1080 in function align_ocr. 
Does it result from this crop_value with hard code?
How can I set the variable of crop_value to adapt to video with size 1920x1080?

**Comment by gortazar** [comment]
Hi @Azson . 

This script was built for a very specific experimentation ([results in this paper](https://www.mdpi.com/2079-9292/9/3/462)), therefore there are some hard coded values. 

However, if you're using the script from the command line, I think you can manually set crop_value as an environment variable, and it will be used within the script. Something in the line:

    crop_value=1234 calculate_qoe_metrics.sh

You will need to specify the value you need (instead of 1234).

Hope it helps.

**Comment by Azson** [comment]
> Hi @Azson .
> 
> This script was built for a very specific experimentation ([results in this paper](https://www.mdpi.com/2079-9292/9/3/462)), therefore there are some hard coded values.
> 
> However, if you're using the script from the command line, I think you can manually set crop_value as an environment variable, and it will be used within the script. Something in the line:
> 
> ```
> crop_value=1234 calculate_qoe_metrics.sh
> ```
> 
> You will need to specify the value you need (instead of 1234).
> 
> Hope it helps.

Hi @gortazar ,
I am glad to get your reply. 
What confuse me is the  calculation of crop_value instead of setting it in command line.
However, I have read the paper before and did not find anything about the explanation of crop_value. It seem some relation to resolution.
```
crop_value=100x45+270+430
if [ $WIDTH -eq 1280 ] && [ $HEIGHT -eq 720 ]; then         
crop_value=100x45+590+670      
fi
```
I use the script `generate_input_video.sh` to label number in a video with size 1920x1080. But it seem some bad performance in `align_ocr`, `calculate_qoe_metrics.sh` due to recognize label bad. I guess it is because the crop_value in origin shell code is not suitable  for the video with 1920x1080. 
So I really want to know how you set the crop_value for different video resolution.

**Comment by Azson** [comment]
I think I find it from [convert crop_value](https://askubuntu.com/questions/631689/cropping-images-using-command-line-tools-only).
Thank you very much!
